#!/usr/bin/env bash
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,git,nvim,zsh,tmux,vim,starship,fish,ghostty,aerospace"
fi

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder -t ~
    stow $folder -t ~
done
